# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [16]:
import numpy as np

#### Create an array of 10 zeros 

In [17]:
array = np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [18]:
array = np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [19]:
array = np.full(10, 5)
print(array)


[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [20]:
array = np.arange(10,51)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [21]:
array = np.arange(10,51, 2)
print(array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
matrix = np.arange(0, 9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [23]:
matrix = np.identity(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [24]:
random_number = np.random.randint(0,1)
print(random_number)

0


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [25]:
random_numbers = np.random.standard_normal(25)
print(random_numbers)

[-0.43373198  0.16937879  1.01793088  0.04254266 -1.45943951  0.06914809
 -0.31865128 -0.45418617 -1.18460199  0.26122001 -1.54779412  0.20720439
 -0.98962148 -0.66684871  1.43648872 -0.64944267  0.36375529  0.51766435
  0.81713926 -0.63022364  0.20895652  1.32050398 -0.69603481  0.39807577
  1.09741295]


#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

In [26]:
array = np.linspace(0,1 ,20)
array

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [27]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [28]:
sum = np.sum(mat)
sum

np.int64(325)

#### Get the standard deviation of the values in mat

In [29]:
standard_deviation = np.std(mat)
standard_deviation

np.float64(7.211102550927978)

#### Get the sum of all the columns in mat

In [30]:
sum_of_columns = np.sum(mat, axis=0)
sum_of_columns



array([55, 60, 65, 70, 75])

# Great Job!