## Exercise No.3

**1-write program for circle class. This class has the following:**
* Attribute: its name is pi with value 3.14
* During the object create the raduis attribute is asigned by the raduis of circle
* Has two methods to calculate the Area and Circumference of circle

In [11]:
class ccircle :
    def __init__(self, raduis):
        pi = 3.14
        self.radis = raduis
        self.area = pi*(raduis)**2
        self.Circumference = 2*pi*raduis
       

**2. Write a program for a Rectangle class.**

Attributes: length and width (set through constructor)

Methods:

area() – returns the area

perimeter() – returns the perimeter

In [12]:
class Rectangle :

   def __init__(self,length,width):
      self.length = length 
      self.width = width

      def area (self):
         area =  self.length * self.width
      return area

      def perimeter (self) :
         perimeter (self.length + self.width) * 2 
      return perimeter

**3-Write a program for an Employee class using class method.**
Attributes: name and salary

Class attribute: company_name

Use a class method to change the company_name for all employees

In [13]:
class Employee :
    company_name = "asd"
    def __init__(self,name,salary):
        self.name = name
        self.salary = salary
    
    @classmethod
    def change_the_company_name(cls, company_new_name):
        cls.company_name = company_new_name
    

    def show (self):
        print(self.name,self.salary,self.company_name)

Employee1 = Employee("karem",2000)
Employee1.show()

Employee.change_the_company_name("ugub")
Employee1.show()

karem 2000 asd
karem 2000 ugub


**4- Create a Shape class and two child classes Square and Circle.**

Use polymorphism to define a method area()

Use a loop to calculate area for both shapes using a common function

In [14]:
class Shape :
    def __init__(self,name):
        self.name = name
    def area():
        pass

class Square(Shape):
    def __init__(self, name , said):
        self.name = name
        self.said = said
    def area(self):
        return self.said * 4

class ccircle (Shape):
    def __init__(self, raduis):
        pi = 3.14
        self.radis = raduis
        self.area = pi*(raduis)**2
        self.Circumference = 2*pi*raduis
       

**5-Create a 1D NumPy array of numbers from 0 to 9**

In [15]:
import numpy as np
array= np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**6-Create a 4x4 NumPy array of all True values**

In [16]:
array1 = np.ones((4,4) , dtype = bool)
array1

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

**7-Create an array of 10 random floats between 0 and 1**

In [17]:
array2= np.random.rand(5,5)
array2

array([[0.02994596, 0.27495618, 0.98049504, 0.82395717, 0.45972976],
       [0.10549061, 0.40134821, 0.87341164, 0.3192998 , 0.35435864],
       [0.05336541, 0.86417759, 0.89680298, 0.76170912, 0.16356444],
       [0.08731828, 0.3971525 , 0.78090325, 0.62516809, 0.30381051],
       [0.10223861, 0.81991499, 0.77189316, 0.17475303, 0.29156434]])

**8-Create a NumPy array of even numbers from 2 to 20**

In [18]:
array3 = np.arange(2,21, 2)
array3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

**9-Get the maximum, minimum, and mean of an random array**

In [19]:
array4 = np.random.randint(0,100 , 10)
array4
maximum =np.max(array4)
minimum =np.min(array4)
mean = np.mean(array4)
print(array4) 
print(maximum)
print(minimum)
print(mean)



[ 7 38 31 75 63 29 30 94 41 91]
94
7
49.9


**10-Flatten a 2D array to 1D**

In [20]:
array5 = np.array([[5, 87], [7, 45]])
array5

array([[ 5, 87],
       [ 7, 45]])